#include:
#  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml

variables:
  TF_ROOT: 'devops/terraform'  # The relative path to the root directory of the Terraform project
  TF_VAR_code_version: ${CI_PIPELINE_IID}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

cache:
  - key: terraform-cache
    paths:
      - ${TF_ROOT}/.terraform

stages:
  - initialize
  - validate
  - build
  - deploy

deploy:dec:
  stage: deploy
  environment: dec
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo "releasing to DEC"

promote:release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  when: manual
  script:
    - echo "Promoting to regular release"
  needs:
    - deploy:dec
  release: #See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'description for 0.0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

deploy:iec:
  stage: deploy
  environment: iec
  rules:
    - if: "$CI_COMMIT_TAG"
      variables:
        VERSION: "$CI_COMMIT_TAG"
  script:
    - echo "releasing to IEC version $VERSION"

deploy:production:
  stage: deploy
  when: manual
  environment: production
  needs:
    - deploy:iec
  rules:
    - if: "$CI_COMMIT_TAG"
      variables:
        VERSION: "$CI_COMMIT_TAG"
  script:
    - echo "releasing to version $VERSION"



validate-user-service-job:
  image: qak87/qak87-ci:latest
  stage: validate
  interruptible: true
  script:
    - user-service/prepareArtifacts.sh
  artifacts:
    paths:
      - devops/contracts-ui/contracts
      - user-service/build
      - user-service/test-reports/coverage.xml
      - user-service/test-reports/nosetests.xml
    reports:
      junit: user-service/test-reports/nosetests.xml
      coverage_report:
        coverage_format: cobertura
        path: user-service/test-reports/coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - user-service/*
        - shared/*

validate-spot-service-job:
  image: amazoncorretto:11.0.16-alpine3.15
  stage: validate
  interruptible: true
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  cache:
    paths:
      - .m2/repository
  script:
    - cd spot-service
    - ../mvnw $MAVEN_OPTS clean package
  artifacts:
    paths:
      - spot-service/target/spot-service-*.jar
      - spot-service/target/surefire-reports/*.xml
    reports:
      junit: spot-service/target/surefire-reports/*.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - spot-service/*
        - shared/*

publish-spot-service-job:
  extends:
    - validate-spot-service-job
  stage: build
  script:
    - cd spot-service
    - ../mvnw $MAVEN_OPTS versions:set -DnewVersion=${CI_PIPELINE_IID}
    - ../mvnw $MAVEN_OPTS clean deploy -s ../ci_settings.xml
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

validate-shared-qkon-job:
  image: qak87/qak87-ci:latest
  stage: validate
  interruptible: true
  script:
    - shared/test.sh
  artifacts:
    paths:
      - shared/test-reports/coverage.xml
      - shared/test-reports/nosetests.xml
    reports:
      junit: shared/test-reports/nosetests.xml
      coverage_report:
        coverage_format: cobertura
        path: shared/test-reports/coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - shared/*
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish-user-service-job: # This job runs in the build stage, which runs first.
  extends:
    - validate-user-service-job
  stage: build
  script:
    - user-service/prepareArtifacts.sh --publish
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

validate-terraform:
  image: qak87/qak87-ci:latest
  stage: validate
  interruptible: true
  script:
    - devops/terraform/validateTerraformFormatting.sh
    - devops/terraform/validateTerraform.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - devops/terraform/*
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


validate-black-job: # This job runs in the build stage, which runs first.
  image: qak87/qak87-ci:latest
  stage: validate
  interruptible: true
  cache: [ ]
  script:
    - ./black.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - user-service/*
        - shared/*
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - user-service/*
        - shared/*
pages:
  stage: deploy
  image: qak87/qak87-ci:latest
  needs:
    - publish-user-service-job
  dependencies:
    - publish-user-service-job
  script:
    - spot-service/devops/prepareContract.sh
    - mv devops/contracts-ui/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
