#include:
#  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml

variables:
  TF_ROOT: 'devops/terraform'  # The relative path to the root directory of the Terraform project
  TF_VAR_code_version: ${CI_PIPELINE_IID}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

cache:
  key: terraform-cache
  paths:
    - ${TF_ROOT}/.terraform

stages:
  - initialize
  - validate
  - build
  - deploy

deploy:dec:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  environment: dec
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo "running release_job"
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '0.0.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'description for 0.0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'



validate-user-service-job:
  image: qak87/qak87-ci:latest
  stage: validate
  script:
    - user-service/prepareArtifacts.sh
  artifacts:
    paths:
      - devops/contracts-ui/contracts
      - user-service/build
      - user-service/test-reports/coverage.xml
      - user-service/test-reports/nosetests.xml
    reports:
      junit: user-service/test-reports/nosetests.xml
      coverage_report:
        coverage_format: cobertura
        path: user-service/test-reports/coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

validate-shared-qkon-job:
  image: qak87/qak87-ci:latest
  stage: validate
  script:
    - shared/test.sh
  artifacts:
    paths:
      - shared/test-reports/coverage.xml
      - shared/test-reports/nosetests.xml
    reports:
      junit: shared/test-reports/nosetests.xml
      coverage_report:
        coverage_format: cobertura
        path: shared/test-reports/coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish-user-service-job: # This job runs in the build stage, which runs first.
  extends:
    - validate-user-service-job
  stage: build
  script:
    - user-service/prepareArtifacts.sh --publish
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

validate-terraform:
  image: qak87/qak87-ci:latest
  stage: validate
  script:
    - devops/terraform/validateTerraformFormatting.sh
    - devops/terraform/validateTerraform.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


validate-black-job: # This job runs in the build stage, which runs first.
  image: qak87/qak87-ci:latest
  stage: validate
  script:
    - ./black.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
pages:
  stage: deploy
  needs:
    - publish-user-service-job
  dependencies:
    - publish-user-service-job
  script:
    - mv devops/contracts-ui/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
