stages:
  - initialize
  - validate
  - build
  - deploy
validate-user-service-job:
  image: qak87/qak87-ci:latest
  stage: validate
  script:
    - user-service/prepareArtifacts.sh
  artifacts:
    paths:
      - devops/contracts-ui/contracts
      - user-service/build
      - user-service/test-reports/coverage.xml
      - user-service/test-reports/nosetests.xml
    reports:
      junit: user-service/test-reports/nosetests.xml
      coverage_report:
        coverage_format: cobertura
        path: user-service/test-reports/coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

validate-shared-qkon-job:
  image: qak87/qak87-ci:latest
  stage: validate
  script:
    - shared/test.sh
  artifacts:
    paths:
      - shared/test-reports/coverage.xml
      - shared/test-reports/nosetests.xml
    reports:
      junit: shared/test-reports/nosetests.xml
      coverage_report:
        coverage_format: cobertura
        path: shared/test-reports/coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish-user-service-job: # This job runs in the build stage, which runs first.
  extends:
    - validate-user-service-job
  stage: build
  script:
    - user-service/prepareArtifacts.sh --publish
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

validate-black-job: # This job runs in the build stage, which runs first.
  image: qak87/qak87-ci:latest
  stage: validate
  script:
    - ./black.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
pages:
  stage: deploy
  needs:
    - publish-user-service-job
  dependencies:
    - publish-user-service-job
  script:
    - mv devops/contracts-ui/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
