---
openapi: 3.0.0
info:
  title: Spot Service Db Layer
  description: The definitions of DynamoDb objects
  contact:
    email: przemek.konstanczuk@gmail.com
  version: 1.0.0
tags:
  - name: dynamo
    description: "Dynamo"
paths:
  /dynamo:
    post:
      summary: dynamo
      operationId: dynamo
      tags:
        - dynamo
      responses:
        "200":
          description: OK
components:
  schemas:
    SpotEntity:
      required:
        - location
        - city
        - token
        - userToken
      properties:
        token:
          $ref: "./../shared/shared.yaml#/SpotToken"
        userToken:
          $ref: "./../shared/shared.yaml#/UserToken"
        location:
          $ref: "./../shared/shared.yaml#/Location"
        name:
          $ref: "./../shared/shared.yaml#/ObjectName"
        city:
          $ref: "./../shared/shared.yaml#/City"